services:
  lampac:
    image: immisterio/lampac:latest
    container_name: lampac
    restart: unless-stopped
    ports:
      - "9118:9118"
    environment:
      - TZ=Europe/Kiev
    volumes:
      # Основна конфігурація
      - ./init.conf:/home/init.conf

      # Конфігурація модулів
      - ./manifest.json:/home/module/manifest.json

      # Файл для автооновлення модулів
      - ./module/repository.yaml:/home/module/repository.yaml

      # Модуль SelfCDN
      - ./module/SelfCDN:/home/module/SelfCDN

      # DLNA медіафайли
      - ./dlna:/home/dlna

      # Тільки settings.json від TorrServer
      - ./torrserver/settings.json:/home/torrserver/settings.json

      # Тільки bookmarks і timecode з cache
      - ./cache/bookmarks:/home/cache/bookmarks
      - ./cache/timecode:/home/cache/timecode
