services:
  lampac:
    image: immisterio/lampac:arm64
    container_name: lampac
    restart: unless-stopped
    ports:
      - "9118:9118"
    environment:
      - TZ=Europe/Kiev
    volumes:
    - ./init.conf:/home/init.conf
    - ./manifest.json:/home/module/manifest.json
    - ./module/repository.yaml:/home/module/repository.yaml
    - ./module/SelfCDN:/home/module/SelfCDN
    - ./dlna:/home/dlna
    - ./torrserver/settings.json:/home/torrserver/settings.json
    - ./database/SyncUser.sql:/home/database/SyncUser.sql
    - ./lampainit.my.js:/home/plugins/lampainit.my.js
    - ./cache/transcoding:/home/cache/transcoding
